### ISSUE TITLE
[Task] check error response on each routes

### ISSUE THREAD

**Issue by minjae-mj** [codestates/waf-server#14]
## Task Card

**Part** : 서버

### Job Description
> 각 라우팅마다 에러 핸들링이 잘 되었는지, 적절한 http 에러 상태코드로 반환하는지 점검

### TODO
1. [ ] users 라우팅 에러 핸들링 확인 (에러 status 코드)
2. [ ] fridges 라우팅 에러 핸들링 확인 (에러 status 코드)
3. [ ] recipes 라우팅 에러 핸들링 확인 (에러 status 코드)

### Labels
Estimated time: E: 1h
Urgency: High, UltraHigh, ExtremelyHigh
